### ISSUE TITLE
Product availability shows outofstock

### ISSUE THREAD

**Issue by s3749653** [karmakatahdin/solidus_seo#12] opened 2020-07-27 02:31 UTC
Hi,

For products with unlimited stock, i have have disabled the track inventory option. For those products they do come up at out of stock in the page source. 

  "offers": {
    "@type": "Offer",
    "priceCurrency": "AUD",
    "price": "19.95",
    "itemCondition": "http://schema.org/NewCondition",
    "availability": "http://schema.org/OutOfStock”
}

Is there a simple way to fix this?

**Comment by jontarg** [comment] 2021-01-15 20:58
Hello!

I reviewed our current implementation and it seems like it should be returning `In stock` whenever there's at least one variant with no inventory tracking. However I've noticed that we excluded considering backorderable items, so I fixed that.

Can you check what's your product returning when calling `variants_including_master.suppliable.any?` on it?

If you want, you can override the `any_in_stock?` method in your product decorator.

**Comment by MFRWDesign** [comment] 2021-01-19 02:18
We couldn't reproduce and have merged a change which we hope will have fixed your issue. Closing.

**Closed by MFRWDesign** 2021-01-19 02:18 UTC
